[package]
name = "math"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[lib]
crate-type = ["cdylib"]

[dependencies]
fasteval = "0.2"
space-lib = "0.5"
serde = { version = "1.0", features = ["derive"] }