[package]
name = "python"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
space-lib = "0.5.1"
rustpython-vm = { git = "https://github.com/RustPython/RustPython", rev = "c3a8d5a9b556b698785d5a34245ce09188ff44a8", no-default-features = true }
proc-macro2 = "1.0.67"
serde = { version = "1.0.145", features = ["derive"] }


[features]
freeze-stdlib = ["rustpython-vm/freeze-stdlib"]
