[workspace]
members = []

[package]
name = "uuid"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[lib]
crate-type = ["cdylib"]

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4", # Lets you generate random UUIDs
    "js",                
]