[package]
name = "environment_variable"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[lib]
crate-type = ["cdylib"]

[dependencies]
hex = "0.4"
md5 = "0.7"
space-lib = "0.5"
