[package]
name = "cmds-solana"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.14"
solana-client = "1.14"
solana-program = "1.14"
spl-token = { version = "3.2", features = ["no-entrypoint"] }
spl-memo = { version = "3.0", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "1.1", features = ["no-entrypoint"] }
mpl-token-metadata = "1.4"
async-trait = "0.1"
tiny-bip39 = "0.8"
inventory = "0.3"
serde = { version = "1", features = ["derive"] }
rust_decimal = { version = "1.26", features = ["maths"] }
bincode = "1"
base64 = "0.13"
serde_json = "1"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls", "gzip"] }
tokio = { version = "1", features = ["time", "macros"] }
mime_guess = "2"
borsh = "0.9"
bytes = "1"
bundlr-sdk = { version = "0.3.0", default-features = false, features = ["solana"] }
ed25519-dalek = "1"
futures = "0.3"
thiserror = "1"
anyhow = "1"
log = "0.4"
serde_with = "2.1"
rhai = "1.10.1"
indexmap = { version = "1.9.1", features = ["serde-1"] }

value = { path = "../value", version = "0.0.1" }
flow-lib = { path = "../flow-lib", version = "0.0.1" }
metaboss_utils = { git = "https://github.com/space-operator/metaboss_utils.git", rev = "9f237fd10b6e5478bf7fd395482d58b71fe2811a" }

[dev-dependencies]
rust_decimal_macros = "1.26"
