[package]
name = "regex"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true

[lib]
crate-type = ["cdylib"]

[dependencies]
regex = "1.6.0"
serde_json = "1.0.87"
serde = { version = "1.0.145", features = ["derive"] }
