name: Rust

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]

jobs:
  clippy-rust:
    name: Clippy lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          profile: default
          override: true
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --tests
  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.65.0
          profile: default
          override: true
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v1
      - name: Test
        run: cargo build --quiet --tests && cargo test
